2023-04-10 14:53:52,682 INFO    MainThread:15796 [wandb_setup.py:_flush():76] Configure stats pid to 15796
2023-04-10 14:53:52,682 INFO    MainThread:15796 [wandb_setup.py:_flush():76] Loading settings from C:\Users\andre\.config\wandb\settings
2023-04-10 14:53:52,682 INFO    MainThread:15796 [wandb_setup.py:_flush():76] Loading settings from D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\settings
2023-04-10 14:53:52,682 INFO    MainThread:15796 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-10 14:53:52,682 INFO    MainThread:15796 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-04-10 14:53:52,682 INFO    MainThread:15796 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-04-10 14:53:52,683 INFO    MainThread:15796 [wandb_init.py:_log_setup():506] Logging user logs to D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_145352-gpxnklzr\logs\debug.log
2023-04-10 14:53:52,683 INFO    MainThread:15796 [wandb_init.py:_log_setup():507] Logging internal logs to D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_145352-gpxnklzr\logs\debug-internal.log
2023-04-10 14:53:52,683 INFO    MainThread:15796 [wandb_init.py:init():546] calling init triggers
2023-04-10 14:53:52,683 INFO    MainThread:15796 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {}
2023-04-10 14:53:52,683 INFO    MainThread:15796 [wandb_init.py:init():568] re-initializing run, found existing run on stack: keaa9tub
2023-04-10 14:53:52,685 INFO    MainThread:15796 [wandb_run.py:_finish():1854] finishing run neural-netwok-nn/neural-network-assgiment2/keaa9tub
2023-04-10 14:53:52,685 INFO    MainThread:15796 [jupyter.py:save_history():445] not saving jupyter history
2023-04-10 14:53:52,685 INFO    MainThread:15796 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-04-10 14:53:52,686 INFO    MainThread:15796 [wandb_init.py:_jupyter_teardown():434] cleaning up jupyter logic
2023-04-10 14:53:52,686 INFO    MainThread:15796 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-04-10 14:53:52,686 INFO    MainThread:15796 [wandb_run.py:_restore():2066] restore
2023-04-10 14:53:52,686 INFO    MainThread:15796 [wandb_run.py:_restore():2072] restore done
2023-04-10 14:54:47,104 INFO    MainThread:15796 [wandb_init.py:init():602] starting backend
2023-04-10 14:54:47,105 INFO    MainThread:15796 [wandb_init.py:init():606] setting up manager
2023-04-10 14:54:47,113 INFO    MainThread:15796 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-04-10 14:54:47,119 INFO    MainThread:15796 [wandb_init.py:init():613] backend started and connected
2023-04-10 14:54:47,127 INFO    MainThread:15796 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2023-04-10 14:54:47,128 INFO    MainThread:15796 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-04-10 14:54:47,128 INFO    MainThread:15796 [wandb_init.py:init():701] updated telemetry
2023-04-10 14:54:47,477 INFO    MainThread:15796 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2023-04-10 14:55:47,990 ERROR   MainThread:15796 [wandb_init.py:init():755] backend process timed out, exiting...
encountered error: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-04-10 14:55:48,012 ERROR   MainThread:15796 [wandb_init.py:init():1171] error
Traceback (most recent call last):
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 1144, in init
    run = wi.init()
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 773, in init
    raise error
wandb.errors.CommError: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
