2023-04-10 15:16:47,610 INFO    MainThread:9752 [wandb_setup.py:_flush():76] Configure stats pid to 9752
2023-04-10 15:16:47,610 INFO    MainThread:9752 [wandb_setup.py:_flush():76] Loading settings from C:\Users\andre\.config\wandb\settings
2023-04-10 15:16:47,610 INFO    MainThread:9752 [wandb_setup.py:_flush():76] Loading settings from D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\settings
2023-04-10 15:16:47,610 INFO    MainThread:9752 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-10 15:16:47,610 INFO    MainThread:9752 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-04-10 15:16:47,610 INFO    MainThread:9752 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-04-10 15:16:47,611 INFO    MainThread:9752 [wandb_init.py:_log_setup():506] Logging user logs to D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_151647-s2x0pzzv\logs\debug.log
2023-04-10 15:16:47,611 INFO    MainThread:9752 [wandb_init.py:_log_setup():507] Logging internal logs to D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_151647-s2x0pzzv\logs\debug-internal.log
2023-04-10 15:16:47,611 INFO    MainThread:9752 [wandb_init.py:_jupyter_setup():452] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000124D3FA06A0>
2023-04-10 15:16:47,612 INFO    MainThread:9752 [wandb_init.py:init():546] calling init triggers
2023-04-10 15:16:47,612 INFO    MainThread:9752 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {}
2023-04-10 15:16:47,612 INFO    MainThread:9752 [wandb_init.py:init():568] re-initializing run, found existing run on stack: lqnx11im
2023-04-10 15:16:47,614 INFO    MainThread:9752 [wandb_run.py:_finish():1854] finishing run neural-netwok-nn/neural-network-assgiment2/lqnx11im
2023-04-10 15:16:47,614 INFO    MainThread:9752 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-04-10 15:16:47,615 INFO    MainThread:9752 [wandb_run.py:_restore():2066] restore
2023-04-10 15:16:47,615 INFO    MainThread:9752 [wandb_run.py:_restore():2072] restore done
2023-04-10 15:38:18,735 INFO    MainThread:9752 [wandb_init.py:init():602] starting backend
2023-04-10 15:38:18,735 INFO    MainThread:9752 [wandb_init.py:init():606] setting up manager
2023-04-10 15:38:18,738 INFO    MainThread:9752 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-04-10 15:38:18,741 INFO    MainThread:9752 [wandb_init.py:init():613] backend started and connected
2023-04-10 15:38:18,746 INFO    MainThread:9752 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2023-04-10 15:38:18,746 INFO    MainThread:9752 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-04-10 15:38:18,747 INFO    MainThread:9752 [wandb_init.py:init():701] updated telemetry
2023-04-10 15:38:18,795 INFO    MainThread:9752 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2023-04-10 15:39:19,336 ERROR   MainThread:9752 [wandb_init.py:init():755] backend process timed out, exiting...
encountered error: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-04-10 15:39:19,371 ERROR   MainThread:9752 [wandb_init.py:init():1171] error
Traceback (most recent call last):
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 1144, in init
    run = wi.init()
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 773, in init
    raise error
wandb.errors.CommError: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
